# sweep.yaml
program: main.py
method: grid      
project: sweep
entity: adammenoud


parameters:
  dataset: 
    values: [arthropods, mushrooms,plants]
  # vectors_name: 
  #   values: [vectors_bioclip, vectors_dino]
  drop_high_freq:
    values: [True, False]

    
  difference: 
        values: [True, False]
