name: geoclip
channels:
  - pytorch
  - esri
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - absl-py=2.1.0
  - affine=2.4.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - annotated-types=0.6.0
  - appdirs=1.4.4
  - asttokens=3.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.10
  - aws-c-common=0.12.5
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.10.1
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.2
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - blas=1.0
  - blinker=1.9.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.12
  - cryptography=46.0.3
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - dill=0.3.8
  - docker-pycreds=0.4.0
  - double-conversion=3.3.1
  - eval_type_backport=0.3.1
  - executing=2.2.1
  - ffmpeg=4.4.0
  - filelock=3.20.0
  - flask=3.1.2
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - freexl=2.0.0
  - frozenlist=1.8.0
  - fsspec=2023.9.2
  - ftfy=6.3.1
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.14.1
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.18
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - grpcio=1.74.1
  - h2=4.3.0
  - h5py=3.14.0
  - harfbuzz=12.2.0
  - hdf5=1.14.5
  - heartrate=0.2.2
  - hf-xet=1.1.8
  - hpack=4.1.0
  - huggingface_hub=0.34.4
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2022.1.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250814.1
  - libarchive=3.8.2
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.6
  - libclang13=21.1.6
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.17.0
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal-core=3.10.3
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm21=21.1.6
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopengl=1.7.0
  - libopentelemetry-cpp-headers=1.21.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=18.1
  - libprotobuf=6.33.0
  - libre2-11=2025.11.05
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.0
  - libuuid=2.41.2
  - libuv=1.48.0
  - libvpx=1.11.0
  - libvulkan-loader=1.4.328.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lightning=2.6.0
  - lightning-utilities=0.15.2
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markdown=3.8
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - minizip=4.0.10
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.0.3
  - mpich=4.3.2
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.15
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.5
  - nlohmann_json=3.11.2
  - numpy=2.3.5
  - ocl-icd=2.3.3
  - open-clip-torch=2.32.0
  - opencl-headers=2025.06.13
  - openh264=2.1.1
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - orc=1.6.4
  - osmnx=2.0.7
  - osmnx-base=2.0.7
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - pooch=1.8.2
  - proj=9.7.0
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=6.33.0
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycares=4.10.0
  - pycparser=2.22
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyogrio=0.11.0
  - pyopenssl=25.3.0
  - pyparsing=3.2.5
  - pyproj=3.7.2
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-gil=3.12.12
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.6.0
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - rasterio=1.4.3
  - re2=2025.11.05
  - readline=8.2
  - regex=2025.9.1
  - regionmask=0.13.0
  - requests=2.32.5
  - rio-vrt=0.3.1
  - s2n=1.6.0
  - safetensors=0.6.2
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - sentencepiece=0.1.99
  - sentry-sdk=2.45.0
  - setproctitle=1.3.7
  - setuptools=80.9.0
  - shapely=2.1.2
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.6.0
  - timm=1.0.14
  - tk=8.6.13
  - tokenizers=0.19.1
  - torchaudio=2.5.1
  - torchinfo=1.8.0
  - torchmetrics=1.8.2
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.40.2
  - typing=3.10.0.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=1.26.19
  - uvloop=0.22.1
  - wandb=0.23.1
  - wayland=1.24.0
  - wcwidth=0.2.14
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!161.3030
  - xarray=2025.11.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.3.0
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.0
  - xyzservices=2025.10.0
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - geoclip==1.2.0
      - geographiclib==2.1
      - geopy==2.4.1
      - sympy==1.13.1
prefix: /home/adam/anaconda3/envs/geoclip
